### ISSUE TITLE
Solar Cells not craftable

### ISSUE THREAD

**Issue by Thundras** [OCB7D2D/ElectricitySolarRecipes#1]
Hello,
I have a problem with the solar cells in version A20. I have the perk advanced engineer at tier 5, but I can't craft the solar cells at the workbench. The solar bank works without any problems. I also get the solar cells displayed at tier 5 but locked. I have also reset the skill points already. I have already looked through the mod files as well but can't find any error.
Can you please help me.
Thanks in advance

Sorry for the German Namings, i hope u will understand

![image](https://user-images.githubusercontent.com/10862226/147864854-bf797414-51bb-4057-ac24-89bc3ffca005.png)
![image](https://user-images.githubusercontent.com/10862226/147864864-03b8c78b-54f6-4760-9225-bbbe2a1889f3.png)

**Comment by mgreter** [comment]
Hi, no problem with german since I'm swiss ;)
Unfortunately can't reproduce what you describe...

https://user-images.githubusercontent.com/282293/147871137-2bb947d1-adfc-46a4-a2b1-2516e8b0af0b.mp4

Please provide a full log, otherwise I can't do anything since not reproducible.
A guess would be that you might have other mods that creates compatibility issues ...

**Comment by Thundras** [comment]
Hi @mgreter,

Thanks for your quick reply. I found the error there was a comma missing in the progression.xml from the mod https://7daystodiemods.com/more-craftable-and-working-lights/ from BastiAKA and JaxTeller718.
Now it works.

**Comment by mgreter** [comment]
Glad you could solve it, maybe give them a heads up so they can fix it ;)
Btw: https://github.com/OCB7D2D/ElectricityLamps  🤷‍♂️😜😄

**Comment by Thundras** [comment]
> Btw: https://github.com/OCB7D2D/ElectricityLamps 🤷‍♂️😜😄

really nice, i will try the mod.

**Comment by mgreter** [comment]
FWIW reported it "upstream": https://community.7daystodie.com/topic/24681-mod-alpha-20-more-craftable-and-working-lights/?do=findComment&comment=462731

**Comment by Thundras** [comment]
> FWIW reported it "upstream": https://community.7daystodie.com/topic/24681-mod-alpha-20-more-craftable-and-working-lights/?do=findComment&comment=462731

thanks
